### ISSUE TITLE
ConditionalField hide values of a Serializable Class on my inspector

### ISSUE THREAD

**Issue by RobertoGlez** [Deadcows/MyBox#61] opened 2020-02-22 21:29 UTC
This is my code
`[ConditionalField("NeedRotation")]
   public RotationCore Rotation;`

And NeedRotation is a bool value, but when is it activated,it show me the class, but do not show me values of the same class, and without this conditional i can see the values without problems, my class have a [System.Serializable] on the top

**Comment by Deadcows** [comment] 2020-04-30 10:37
Oh my, how did I missed that! Sorry for the late response!

I tried to reproduce the issue:
```
public class Test : MonoBehaviour
{
  public bool A;
  [ConditionalField(nameof(A))] public TestStruct TTest;
}

[Serializable]
public struct TestStruct
{
  public string A;
  public int B;
}
```

it works as intended:
![image](https://user-images.githubusercontent.com/969858/80701083-7e580e80-8ae7-11ea-89b9-0ad9e92289c1.png)

Do you have custom drawer for RotationCore or some other specifics that differ your case from my test?

**Comment by Deadcows** [comment] 2020-05-06 06:10
I'll close it for now, will reopen if problem remains. I'm working on the remake of ConditionalField anyway

**Closed by Deadcows** 2020-05-06 06:10 UTC
