### ISSUE TITLE
Update doesn't work

### ISSUE THREAD

**Issue by Tymski** [Deadcows/MyBox#124] opened 2021-02-23 19:30 UTC
Your script says to update, but there is no new version in the package manager.
The update button doesn't work.
There is no .unitypackage in the releases section.
There is no version tag in the manifest URL.
![image](https://user-images.githubusercontent.com/8183632/108896965-d8e1ce80-7615-11eb-8729-8d54c0c6c982.png)
![image](https://user-images.githubusercontent.com/8183632/108896551-5e18b380-7615-11eb-94d6-93f1c1d58a3c.png)
![image](https://user-images.githubusercontent.com/8183632/108896586-6a047580-7615-11eb-8806-e4622cfddbc1.png)
![image](https://user-images.githubusercontent.com/8183632/108896673-830d2680-7615-11eb-86b8-a1d1b097a79e.png)

**Comment by Garfounkel** [comment] 2021-03-05 15:33
Duplicate of #117. Just change the package name from "com.mybox" to "com.domybest.mybox" in the manifest.json and you should be good.

**Closed** 2021-03-18 15:14 UTC
